#!/usr/bin/env bash
set -euo pipefail

# --- Pi Agent Installer ---
# Builds the Docker image, configures shell alias, and sets up API keys.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IMAGE_NAME="pi-agent"
ALIAS_MARKER="# [pi-agent-alias]"
OLLAMA_MARKER="# [pi-agent-ollama]"

# Colors
bold="\033[1m"
dim="\033[2m"
green="\033[32m"
yellow="\033[33m"
cyan="\033[36m"
reset="\033[0m"

info()  { echo -e "${cyan}>>>${reset} $*"; }
ok()    { echo -e "${green}>>>${reset} $*"; }
warn()  { echo -e "${yellow}>>>${reset} $*"; }

# --- Detect shell rc file ---
detect_rc_file() {
    local shell_name
    shell_name="$(basename "${SHELL:-/bin/bash}")"
    case "$shell_name" in
        zsh)  echo "$HOME/.zshrc" ;;
        *)    echo "$HOME/.bashrc" ;;
    esac
}

RC_FILE="$(detect_rc_file)"

# --- Step 1: Ollama host ---
echo ""
info "Where is Ollama running?"
echo -e "    ${dim}Local machine:  http://localhost:11434${reset}"
echo -e "    ${dim}Remote machine: http://192.168.1.x:11434${reset}"
read -rp "    Ollama host URL [http://localhost:11434]: " ollama_input
OLLAMA_HOST="${ollama_input:-http://localhost:11434}"
ok "Using Ollama host: ${bold}${OLLAMA_HOST}${reset}"

# --- Step 2: Build Docker image ---
echo ""
info "Building Docker image ${bold}${IMAGE_NAME}${reset}..."
docker build \
    --build-arg UID="$(id -u)" \
    --build-arg GID="$(id -g)" \
    -t "$IMAGE_NAME" \
    "$SCRIPT_DIR"
ok "Image built."

# --- Step 3: Check Ollama ---
info "Checking Ollama at ${OLLAMA_HOST}..."
if curl -s "${OLLAMA_HOST}/api/tags" > /dev/null 2>&1; then
    model_count=$(curl -s "${OLLAMA_HOST}/api/tags" | python3 -c "import sys,json; print(len(json.load(sys.stdin).get('models',[])))" 2>/dev/null || echo "0")
    if [ "$model_count" -eq 0 ]; then
        warn "Ollama is running but no models are installed."
        echo -e "    Recommended: ${bold}ollama pull qwen2.5-coder:32b${reset}"
        read -rp "    Pull qwen2.5-coder:32b now? [Y/n] " pull_model
        if [[ "${pull_model:-Y}" =~ ^[Yy]$ ]]; then
            ollama pull qwen2.5-coder:32b
        fi
    else
        ok "Ollama is running with $model_count model(s)."
    fi
else
    warn "Could not reach Ollama at ${OLLAMA_HOST}."
    if [[ "$OLLAMA_HOST" == *"localhost"* ]]; then
        echo "    Install from https://ollama.com and pull a model:"
        echo "    ollama pull qwen2.5-coder:32b"
    else
        echo "    Make sure Ollama is running on the remote machine and"
        echo "    that OLLAMA_HOST is set to 0.0.0.0 on the remote:"
        echo "    OLLAMA_HOST=0.0.0.0 ollama serve"
    fi
fi

# --- Step 4: API keys ---
info "Configuring API keys..."

# Kagi
existing_kagi=$(grep -oP 'export KAGI_API_KEY="\K[^"]*' "$RC_FILE" 2>/dev/null || true)
if [ -n "$existing_kagi" ]; then
    ok "Kagi API key already configured."
else
    echo ""
    echo -e "    ${bold}Kagi Search${reset} ${dim}(optional, for fast web search)${reset}"
    echo -e "    Get a key at: ${cyan}https://kagi.com/settings?p=api${reset}"
    read -rp "    Enter Kagi API key (or press Enter to skip): " kagi_key
    if [ -n "$kagi_key" ]; then
        sed -i '/^export KAGI_API_KEY=/d' "$RC_FILE" 2>/dev/null || true
        echo "export KAGI_API_KEY=\"$kagi_key\"" >> "$RC_FILE"
        export KAGI_API_KEY="$kagi_key"
        ok "Kagi API key saved to $RC_FILE"
    else
        echo "    Skipped. You can add it later:"
        echo "    echo 'export KAGI_API_KEY=\"your-key\"' >> $RC_FILE"
    fi
fi

# --- Step 5: Write OLLAMA_HOST to RC ---
info "Saving Ollama host to $RC_FILE..."

OLLAMA_EXPORT="export OLLAMA_HOST=\"${OLLAMA_HOST}\""
if grep -qF "$OLLAMA_MARKER" "$RC_FILE" 2>/dev/null; then
    awk -v marker="$OLLAMA_MARKER" -v val="$OLLAMA_EXPORT" '
        $0 == marker { print; getline; print val; next }
        { print }
    ' "$RC_FILE" > "${RC_FILE}.tmp" && mv "${RC_FILE}.tmp" "$RC_FILE"
    ok "Updated OLLAMA_HOST in $RC_FILE"
else
    { echo ""; echo "$OLLAMA_MARKER"; echo "$OLLAMA_EXPORT"; } >> "$RC_FILE"
    ok "Saved OLLAMA_HOST to $RC_FILE"
fi

# --- Step 6: Generate .env for docker-compose ---
info "Generating .env for docker-compose..."
cat > "${SCRIPT_DIR}/.env" <<EOF
# Generated by install.sh — edit to change settings
OLLAMA_HOST=${OLLAMA_HOST}
KAGI_API_KEY=${KAGI_API_KEY:-}
UID=$(id -u)
GID=$(id -g)
EOF
ok "Written to ${SCRIPT_DIR}/.env"

# --- Step 7: Shell alias ---
info "Configuring shell alias..."

ALIAS_LINE="alias pi='docker run -it --rm --network host -v \"\$(pwd):/workspace\" -v \"\$HOME/.pi:/home/piuser/.pi\" -e KAGI_API_KEY=\"\${KAGI_API_KEY}\" -e OLLAMA_HOST=\"\${OLLAMA_HOST:-http://localhost:11434}\" ${IMAGE_NAME}'"

if grep -qF "$ALIAS_MARKER" "$RC_FILE" 2>/dev/null; then
    awk -v marker="$ALIAS_MARKER" -v alias_line="$ALIAS_LINE" '
        $0 == marker { print; getline; print alias_line; next }
        { print }
    ' "$RC_FILE" > "${RC_FILE}.tmp" && mv "${RC_FILE}.tmp" "$RC_FILE"
    ok "Updated existing pi alias in $RC_FILE"
else
    {
        echo ""
        echo "$ALIAS_MARKER"
        echo "$ALIAS_LINE"
    } >> "$RC_FILE"
    ok "Added pi alias to $RC_FILE"
fi

# --- Done ---
echo ""
echo -e "${green}${bold}Installation complete!${reset}"
echo ""
echo "    Restart your shell or run:"
echo -e "    ${bold}source $RC_FILE${reset}"
echo ""
echo "    Then start the agent from any project directory:"
echo -e "    ${bold}pi${reset}"
echo ""
echo "    To change Ollama host later:"
echo -e "    Edit ${bold}OLLAMA_HOST${reset} in $RC_FILE (and .env for compose)"
echo ""
echo -e "    Live browser: ${cyan}http://localhost:6080/vnc.html${reset}"
echo ""
